FROM postgres:15

RUN apt-get update && apt-get install -y --no-install-recommends \
      postgresql-15-pgtt \
      postgresql-15-orafce \
      postgresql-15-cron \
      postgresql-contrib \
      postgresql-15-xml2 \
    && rm -rf /var/lib/apt/lists/*

# postgres_fdw and hstore ship inside postgresql-contrib, no separate package

RUN echo "shared_preload_libraries = 'pg_cron'" >> /usr/share/postgresql/postgresql.conf.sample && \
    echo "cron.database_name = 'target_db'" >> /usr/share/postgresql/postgresql.conf.sample

EXPOSE 5432
